const images = {
    logo: require("../Images/logo.png"),
    upArrowIcon: require("../Images/upArrowIcon.png"),
    gps_icon: require("../Images/gps_icon.png"),
    explore_active: require("../Images/explore_active.png"),
    search_inactive: require("../Images/search_inactive.png"),
    cart_inactive: require("../Images/cart_inactive.png"),
    connections_inactive: require("../Images/connections_inactive.png"),
    account_inactive: require("../Images/account_inactive.png"),
    location_2: require("../Images/location_icon.png"),

    card_bg: require("../Images/select_card_bakc.png"),
    select_language: require("../Images/Select_language.jpg"),
    arabic_icon: require("../Images/arabic.png"),
    english_icon: require("../Images/english_icon.png"),
    water_bottle: require("../Images/water_bottle.png"),
    water_tanker: require("../Images/water_tanker.png"),
    donate_icon: require("../Images/donate_icon.png"),
    home_icon_active: require("../Images/home_icon_active.png"),
    order_history_active: require("../Images/order_icon_active.png"),
    order_history_inactive: require("../Images/order_history_inactive.png"),
    profile_inactive: require("../Images/profile_inactive.png"),
    profile_active: require("../Images/profile_active_icon.png"),
    location_icon_white: require("../Images/location_icon_white.png"),
    filetr_card_bg: require("../Images/filetr_card_bg.png"),
    back_white: require("../Images/back_white.png"),
    water_bottel_icon: require("../Images/water_bottel_icon.png"),
    gallon_icon: require("../Images/gallon_icon.png"),
    filter_icon: require("../Images/filter_icon.png"),
    star_active: require("../Images/star_active.png"),
    inactive_star: require("../Images/inactive_star.png"),
    minus_count: require("../Images/minus_count.png"),
    plus_count: require("../Images/plus_count.png"),
    price_bg: require("../Images/price_bg.png"),
    orders_icon_white: require("../Images/orders_icon_white.png"),
    froward_white: require("../Images/froward_white.png"),
    splash_screen2: require("../Images/splash_screen2.jpg"),
    dropdown_icon: require("../Images/dropdown_icon.png"),
    name_icon: require("../Images/name_icon.png"),
    profile_pic: require("../Images/profile_pic.png"),
    phone: require("../Images/phone.png"),
    setting: require("../Images/setting.png"),
    delivery_reached: require("../Images/delivery_reached.png"),
    payment_recieved: require("../Images/payment_recieved.png"),
    ratings_icon_filled: require("../Images/ratings_icon_filled.png"),
    ratings_icon_unfilled: require("../Images/ratings_icon_unfilled.png"),
    saudi_flag: require("../Images/saudi_flag.png"),
    thangs_itenery:  require("../Images/thangs_itenery.png"),

    //aldana:  require("../Images/water_brand/aldana.jpg"),
    arwa: require("../Images/water_brand/arwa.jpg"),
    berain: require("../Images/water_brand/berain.jpg"),
    brand: require("../Images/water_brand/brand.jpg"),
    dala: require("../Images/water_brand/dala.jpg"),
    evina: require("../Images/water_brand/evina.jpg"),
    fat: require("../Images/water_brand/fat.jpg"),
    fiji: require("../Images/water_brand/fiji.png"),
    hana: require("../Images/water_brand/hana.jpg"),
    hilwa: require("../Images/water_brand/hilwa.jpg"),
    icz: require("../Images/water_brand/icz.jpg"),
    lull: require("../Images/water_brand/lull.jpg"),
    moya: require("../Images/water_brand/moya.png"),
    naql: require("../Images/water_brand/naql.jpg"),
    other: require("../Images/water_brand/other.png"),
    //pipj:  require("../Images/water_brand/pipj.jpeg"),
    //pure: require("../Images/water_brand/pure.jpg"),
    ulu: require("../Images/water_brand/ulu.jpg"),
    valina: require("../Images/water_brand/valina.jpg"),
    vodavoda: require("../Images/water_brand/vodavoda.jpg"),

    //from groceroze
    grocery: require('../Images/grocery.png'),
    food: require('../Images/food.png'),
    banner: require('../Images/banner.png'),
    iconCat: require('../Images/iconCat.png'),
    productImage: require('../Images/productImage.png'),


    payPal: require("../Images/ic_paypal.png"),
    visaCard: require("../Images/ic_visa.png"),
    masterCard: require("../Images/ic_master_card.png"),
    discover: require("../Images/ic_discover.png"),

    oxygen: require("../Images/oxygen.png"),
};

export default images;
