import {Platform, StyleSheet, Dimensions, I18nManager} from 'react-native';
// Screen Styles
const {width, height} = Dimensions.get('window');

import {Fonts, Metrics, Colors} from '../Themes';

const styles = StyleSheet.create({
  screenBg: {
    backgroundColor: Colors.branding_color,
  },
  containerSplash: {
    height: '100%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoStyle: {
    height: 152.53,
    width: 158.95,
  },
  sideBottomImage: {
    height: 200,
    width: 122,
    position: 'absolute',
    left: 0,
    bottom: 0,
  },
  footerText: {
    color: Colors.branding_color,
    position: 'absolute',
    bottom: 10,
    fontSize: 23,
  },
  header_style: {
    paddingTop: 14,
    height: Fonts.moderateScale(65),
    //backgroundColor: Colors.red,
    backgroundColor: Colors.transparent,
    borderBottomWidth: 0,
    elevation: 0,
  },
  login_title: {
    color: Colors.snow,
    fontWeight: 'bold',
    fontFamily: Fonts.type.avenirNextBold,
    fontSize: Fonts.moderateScale(20),
  },
  body: {
    flex: 2,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  right: {
    flex: 0.5,
  },
  container: {
    height: '100%',
    //marginTop: Fonts.moderateScale(192),
    backgroundColor: Colors.snow,
    borderTopRightRadius: 38,
    borderTopLeftRadius: 38,
    paddingLeft: Fonts.moderateScale(17),
    paddingRight: Fonts.moderateScale(17),
    paddingTop: Fonts.moderateScale(30),
  },
  imgContainer: {
    height: '90%',
    justifyContent: 'center', //Centered vertically
    alignItems: 'center', // Centered horizontally
    flex: 1,
  },
  inputFieldSec: {
    marginTop: '30%',
  },
  title_text_m: {
    fontWeight: 'bold',
    fontSize: 24,
    color: Colors.black,
    marginTop: Fonts.moderateScale(10),
  },
  textInput: {
    flexDirection: 'row',
    borderRadius: Metrics.HEIGHT * 0.01,
    marginTop: 35,
    height: Fonts.moderateScale(47),
    width: Metrics.WIDTH * 0.86,
    paddingLeft: 25,
    paddingRight: 25,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: Fonts.moderateScale(14),
    //////fontFamily: Fonts.type.sfuiDisplayRegular,
    backgroundColor: 'white',
    //paddingVertical: 16,
    //paddingHorizontal: 16,
    //borderRadius: 12,
    borderColor: 'lightgray',
    borderWidth: StyleSheet.hairlineWidth,
    shadowColor: '#00000015',
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 4,
    shadowOffset: {
      width: 0,
      height: 4,
    },
  },
  icon_l: {
    marginLeft: Fonts.moderateScale(5),
  },
  row_half: {
    marginLeft: Fonts.moderateScale(8),
    height: Fonts.moderateScale(28),
    borderWidth: 0.8,
    borderColor: Colors.lightGray,
  },
  text_input: {
    marginLeft: 5,
    width: Metrics.WIDTH * 0.59,
  },
  chboxConatiner: {
    flexDirection: 'row',
    marginTop: Fonts.moderateScale(15),
    width: Metrics.WIDTH * 0.84,
    //height: Metrics.HEIGHT * 0.07,
    alignItems: 'center',
    alignSelf: 'center',
  },
  chboxRemember: {
    width: 25,
    height: 25,
    borderRadius: 10,
  },
  textRememberMe: {
    borderBottomWidth: 1,
    borderBottomColor: Colors.branding_color,
    color: Colors.black,
    fontSize: Fonts.moderateScale(16),
    fontFamily: Fonts.type.sfuiDisplayRegular,
    marginLeft: Fonts.moderateScale(20),
  },
  fbTwitter2: {
    alignSelf: 'center',
    width: Metrics.WIDTH * 0.84,
    marginTop: Fonts.moderateScale(29),
    marginBottom: Fonts.moderateScale(23),
    //height: Metrics.HEIGHT * 0.13,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnFb2: {
    backgroundColor: Colors.branding_color,
    borderRadius: Metrics.HEIGHT * 0.04,
    flexDirection: 'row',
    //borderWidth: 1,
    //borderColor: '#3b5998',
    width: Metrics.WIDTH * 0.82,
    height: Fonts.moderateScale(45),
    justifyContent: 'center',
    alignItems: 'center',
  },
  fbText: {
    color: Colors.snow,
    fontSize: Fonts.moderateScale(14),
    fontWeight: 'bold',
    marginLeft: Fonts.moderateScale(5),
  },
  head_text: {
    textAlign: 'center',
    color: Colors.color_one,
    fontWeight: 'bold',
  },
  dsc_text: {
    textAlign: 'center',
    marginTop: 10,
    color: Colors.color_one,
    fontWeight: 'bold',
  },
  view2_otp: {
    width: '100%',
    marginTop: 50,
    marginBottom: 10,
    alignItems: 'center',
  },
  underlineStyleBase: {
    width: 50,
    height: 53,
    borderRadius: 10,
    borderWidth: 0,
    //borderBottomWidth: 1.3,
    borderColor: Colors.black,
    color: '#A159D1',
    fontSize: 16,
    fontWeight: 'bold',
    backgroundColor: 'rgba(161, 89, 209, 0.2)',
  },

  underlineStyleHighLighted: {
    //borderBottomWidth: 1.3,
    //borderColor: Colors.black,
  },
  top_select: {
    marginTop: Fonts.moderateScale(30),
    marginLeft: Fonts.moderateScale(10),
    marginRight: Fonts.moderateScale(10),
    alignItems: 'flex-start',
  },
  title_text: {
    fontSize: Fonts.moderateScale(24),
    fontWeight: '500',
  },
  card_top_margin: {
    marginTop: Fonts.moderateScale(28),
    //marginLeft: Fonts.moderateScale(10),
    // /marginRight: Fonts.moderateScale(10),
  },
  card_image_style: {
    height: Metrics.HEIGHT * 0.25,
    width: 99 + '%',
    resizeMode: 'stretch',
  },
  brandName: {
    fontSize: 20,
    fontWeight: 'bold',
    marginHorizontal: 18,
    color: Colors.snow,
    marginBottom: 8,
  },
  header_style2: {
    alignItems: 'center',
    height: Fonts.moderateScale(65),
    //backgroundColor: Colors.red,
    backgroundColor: Colors.transparent,
    borderBottomWidth: 0,
    elevation: 0,
    marginHorizontal: 10,
    flexDirection: 'row',
  },
  walletButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.snow,
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 8,
  },
  selectLocationButton: {
    margin: 8,
    flexDirection: 'row',
    height: 35,
    paddingHorizontal: 18,
    backgroundColor: Colors.snow,
    elevation: 5,
    alignItems: 'center',
    borderRadius: 20,
  },
  selectLocationText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: Colors.branding_color2,
  },
  fullWidthView: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 120,
  },
  bannerSize: {
    height: 252,
    marginTop: 10,
  },
  catSectionMain: {
    flexDirection: 'row',
    //flexWrap: 'wrap',
    marginTop: 10,
  },
  catSectionMainWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
  },
  catBox: {
    width: Metrics.WIDTH * 0.43,
    height: 137,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.shadows,
    borderRadius: 10,
    marginLeft: Metrics.WIDTH * 0.01,
    marginRight: Metrics.WIDTH * 0.01,
    marginTop: 10,
  },
  catIcon: {
    height: 75,
    width: 75,
  },
  catHead: {
    color: '#EBB881',
    fontSize: 12,
    marginTop: 5,
    fontWeight: 'bold',
  },
  catCount: {
    fontSize: 10,
    color: Colors.color_one,
  },
  catBoxProduct: {
    width: Metrics.WIDTH * 0.35,
    marginRight: Metrics.WIDTH * 0.03,
    marginTop: 10,
  },
  catImageProduct: {
    width: Metrics.WIDTH * 0.35,
    height: Metrics.WIDTH * 0.35,
  },
  catHeadProduct: {
    color: Colors.color_one,
    fontSize: 13,
    marginTop: 5,
    fontWeight: 'bold',
  },
  catSubProduct: {
    color: Colors.branding_color,
    fontSize: 16,
    marginTop: 5,
  },
  catPricingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
    paddingHorizontal: 5,
  },
  catPriceDiscounted: {
    fontSize: 14,
    color: Colors.green,
  },
  catPrice: {
    fontSize: 14,
    textDecorationLine: 'line-through',
    color: Colors.color_one,
  },
  productCart: {
    marginTop: 20,
    width: Metrics.WIDTH * 0.9,
    flexDirection: 'row',
  },
  productDscSection: {
    width: Metrics.WIDTH * 0.38,
    marginLeft: 8,
    color: Colors.snow,
  },
  productTitle: {
    fontSize: 18,
    color: Colors.second_color,
    fontWeight: 'bold'
  },
  cardPrice: {
    marginLeft: 'auto',
    color: Colors.color_one,
    fontSize: 14,
    fontWeight: 'bold'
  },
  cardPriceCross: {
    marginLeft: 'auto',
    color: Colors.color_one,
    fontSize: 14,
    textDecorationLine: 'line-through',
    fontWeight: 'bold'
  },
  cardQuantity: {
    color: Colors.color_one,
    fontSize: 14,
  },
  plusMinusContainer: {
    marginTop: 20,
    width: Metrics.WIDTH * 0.32,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  plusMinusSize: {
    borderRadius: 5,
    height: 30,
    width: 30,
    backgroundColor: Colors.cloud,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleOfTagLine: {
    fontSize: 15,
    color: Colors.branding_color2,
    fontWeight: 'bold',
  },
  container_unactive: {
    height: Metrics.HEIGHT,
    marginTop: Fonts.moderateScale(0),
    backgroundColor: Colors.snow,
    borderTopRightRadius: 38,
    borderTopLeftRadius: 38,
    //paddingLeft: Fonts.moderateScale(17),
    //paddingRight: Fonts.moderateScale(17),
    paddingTop: Fonts.moderateScale(30),
  },
  container_active: {
    height: Metrics.HEIGHT,
    marginTop: Fonts.moderateScale(0),
    paddingBottom: Fonts.moderateScale(10),
    backgroundColor: Colors.snow,
    borderTopRightRadius: 38,
    borderTopLeftRadius: 38,
    borderBottomLeftRadius: 38,
    borderBottomRightRadius: 38,
    paddingTop: Fonts.moderateScale(30),
  },
  footer_style_file: {
    paddingHorizontal: Fonts.moderateScale(12),
    justifyContent: 'space-between',
    elevation: 0,
    shadowOpacity: 0,
    borderBottomWidth: 0,
    backgroundColor: Colors.transparent,
    paddingTop: Fonts.moderateScale(4),
    height: Fonts.moderateScale(50),
    flexDirection: 'row',
  },
  productAddedText: {
    fontSize: 12,
    color: Colors.snow,
    marginLeft: 10,
    fontWeight: 'bold',
  },
  productAddedText2: {
    fontSize: 12,
    color: Colors.snow,
    marginRight: 10,
    fontWeight: 'bold',
  },
  slidesec: {
    height: 197,
    backgroundColor: Colors.snow,
  },
  activeDot: {
    backgroundColor: Colors.branding_color,
    width: Metrics.WIDTH * 0.02,
    height: Metrics.WIDTH * 0.02,
    borderRadius: Metrics.WIDTH * 0.01,
    marginLeft: Metrics.WIDTH * 0.005,
    marginRight: Metrics.WIDTH * 0.005
  },
  sliderImage: {
    resizeMode: "contain",
    backgroundColor: Colors.snow,
    height: 170,
    borderRadius: 8,
    marginTop: Fonts.moderateScale(20),
    //marginLeft: (Metrics.WIDTH * 0.02),
    //marginRight: (Metrics.WIDTH * 0.02),
    //width: (Metrics.WIDTH * 0.92),


  },
  tabsGap:{
    marginLeft: 10,
    marginRight: 10,
  },
  top_tab: {
    width: '100%',
    flexDirection: 'row',
    backgroundColor: Colors.snow,
    paddingLeft: Fonts.moderateScale(20),
    paddingRight: Fonts.moderateScale(20),
    //paddingVertical: Fonts.moderateScale(25),
  },
  tab_text: {
    color: Colors.second_color,
    fontSize: Fonts.moderateScale(18),
  },
  tab_text_unacitive: {
    fontSize: Fonts.moderateScale(18),
    color: Colors.branding_color,
  },
  border_tab: {
    marginTop: Fonts.moderateScale(10),
    borderBottomWidth: 2,
    borderColor: Colors.branding_color,
    width: Fonts.moderateScale(40),
  },
  border_tab_unactive: {
    marginTop: Fonts.moderateScale(10),
    borderBottomWidth: 2,
    borderColor: Colors.snow,
    width: Fonts.moderateScale(40),
  },
  itememail: {
    marginLeft: Fonts.moderateScale(6),
    backgroundColor: Colors.snow,
    alignSelf: "center",
    borderBottomWidth: 0.7,
    borderBottomColor: Colors.snow,
    marginTop: Fonts.moderateScale(4),
    //width: Metrics.WIDTH * 0.88,
    height: Fonts.moderateScale(40),
    borderRadius: 20,
  },
});
export default styles;
